GET http://localhost:3000/api/admins

###

GET http://localhost:3000/api/admins/645a63f88c61272ab2f74223

###

POST http://localhost:3000/api/admins/signup
Content-Type: application/json

{
    "name": "Capo",
    "surname": "Supremo",
    "email": "capo@sup.it",
    "password": "pass123"
}

###

DELETE http://localhost:3000/api/admins/645a64318c61272ab2f7422b

###

PATCH http://localhost:3000/api/admins/645a63f88c61272ab2f74223
Content-Type: application/json

{
    "email": "pippo@baudo.it",
    "password": "kikkko"
}

###

POST http://localhost:3000/api/admins/login
Content-Type: application/json

{
    "email": "capo@sup.it",
    "password": "pass123"
}
###

POST http://localhost:3000/api/admins/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY3NDNiZDViNjE3MWQyZTFhZDU3NGMiLCJuYW1lIjoiQ2FwbyIsInN1cm5hbWUiOiJTdXByZW1vIiwiZW1haWwiOiJjYXBvQHN1cC5pdCIsInBhc3N3b3JkIjoiJDJiJDEwJHhPcWs1UGhJeHdoNjAzb3FzNG9VTGUyV05iRlBUWjVFNlFKNXhiM2kwSWFDd3ZEU1VtUFVLIiwiX192IjowLCJpYXQiOjE2ODQ0ODkzNDB9.YRVJad7aA-tBXzd9KRosQ801d5PWQ4U93nhP_YlOlLQ