GET http://localhost:3000/students

###

GET http://localhost:3000/students/645a69a4b2ad03dc07295897

###

POST http://localhost:3000/students
Content-Type: application/json

{
    "name": "francesco",
    "surname": "la rosa",
    "gender": "M",
    "email": "prova@x",
    "password": "123",
    "student_id": "123456",
    "study_course": "matematica",
    "study_year": "2020"
}

###

DELETE http://localhost:3000/students/6464cc78c885285a22ad431f

###

PATCH http://localhost:3000/students/645a63838c61272ab2f74214
Content-Type: application/json

{
    "gender": "F",
    "password": "67890"
}

###

POST http://localhost:3000/students/login
Content-Type: application/json

{
    "email": "prova@x",
    "password": "123"
}

###

POST http://localhost:3000/students/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY0Y2QyZGM4ODUyODVhMjJhZDQzMzUiLCJuYW1lIjoiZnJhbmNlc2NvIiwic3VybmFtZSI6ImxhIHJvc2EiLCJnZW5kZXIiOiJNIiwiZW1haWwiOiJwcm92YUB4IiwicGFzc3dvcmQiOiIkMmIkMTAkU2MybE9ZZ3cxYXd1Zjg1VkptMU5GLks2ZkVnZldKdWNxNnRudEtwUU5EdHBhSUYuQm1vdXkiLCJzdHVkZW50X2lkIjoiMTIzNDU2Iiwic3R1ZHlfY291cnNlIjoibWF0ZW1hdGljYSIsInN0dWR5X3llYXIiOiIyMDIwIiwiX192IjowLCJpYXQiOjE2ODQzMjc3Mzh9.KpOTnVlkFGHh9ffhA3BJVJfh1F59_cQVdI2XlJvOLNA