GET http://localhost:3000/api/admins/getall

###

GET http://localhost:3000/api/admins/getadmin/645a6a34fc4bbc2a137ab299

###

POST http://localhost:3000/api/admins/signup
Content-Type: application/json

{
    "name": "Mario",
    "surname": "Rossi",
    "email": "m.rossi@gmail.it",
    "password": "pass123"
}

###

DELETE http://localhost:3000/api/admins/deleteadmin/6469db0d9acd0a9eed299d56

###

PATCH http://localhost:3000/api/admins/updateAdmin/6469db0d9acd0a9eed299d56
Content-Type: application/json

{
    "email": "nanni@nonno.it",
    "password": "kikkko"
}

###

POST http://localhost:3000/api/admins/login
Content-Type: application/json

{
    "email": "capo@sup.it",
    "password": "pass123"
}
###

POST http://localhost:3000/api/admins/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY5ZGIwZDlhY2QwYTllZWQyOTlkNTYiLCJuYW1lIjoiTm9ubm8iLCJzdXJuYW1lIjoiTmFubmkiLCJlbWFpbCI6Im5hbm5pQG5vbm5vLml0IiwicGFzc3dvcmQiOiIkMmIkMTAkU2hJcUhxOWVNYU5PTGcvYVJLUlJrdXpZcmhKeWRDb2NBMkZiVDVKbXF2aS5sZ0VhSm5WODYiLCJfX3YiOjAsImlhdCI6MTY4NDY1OTA0N30.eB4DuLFYr7zMhx1VVGqGUkC0ynmbrMDpwNfvookj0zE

### STUDENTS

DELETE http://localhost:3000/api/admins/studentManager/deletestudent/6469dbe59acd0a9eed299d68

###

PATCH http://localhost:3000/api/admins/studentManager/updatestudent/6469dbe59acd0a9eed299d68
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY3NDNiZDViNjE3MWQyZTFhZDU3NGMiLCJuYW1lIjoiQ2FwbyIsInN1cm5hbWUiOiJTdXByZW1vIiwiZW1haWwiOiJjYXBvQHN1cC5pdCIsInBhc3N3b3JkIjoiJDJiJDEwJHhPcWs1UGhJeHdoNjAzb3FzNG9VTGUyV05iRlBUWjVFNlFKNXhiM2kwSWFDd3ZEU1VtUFVLIiwiX192IjowLCJpYXQiOjE2ODUwMDYwNDd9.XOFDTjNnWvQl3TA2UY8RuGZXfp7eGvaemcDQ1U_5gEg
Content-Type: application/json

{
    "email": "ninella@ehehihi",
    "student_id": "202020",
    "study_course": "veterinaria",
    "study_year": "2023"
}

###

GET http://localhost:3000/api/admins/studentManager/getstudent/6467412bd9a20eceb3b96475

###

GET http://localhost:3000/api/admins/studentManager/getstudents
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY3NDNiZDViNjE3MWQyZTFhZDU3NGMiLCJuYW1lIjoiQ2FwbyIsInN1cm5hbWUiOiJTdXByZW1vIiwiZW1haWwiOiJjYXBvQHN1cC5pdCIsInBhc3N3b3JkIjoiJDJiJDEwJHhPcWs1UGhJeHdoNjAzb3FzNG9VTGUyV05iRlBUWjVFNlFKNXhiM2kwSWFDd3ZEU1VtUFVLIiwiX192IjowLCJpYXQiOjE2ODUwMDYwNDd9.XOFDTjNnWvQl3TA2UY8RuGZXfp7eGvaemcDQ1U_5gEg

### EVENTS

GET http://localhost:3000/api/admins/createEvent

{
    "name": "Quarto evento da user input",
    "location": "Pizzeria bell'Italia",
    "description": "Speriamo funzioni",
    "startDate": "2023-06-1T10:18:03.000Z",
    "endDate": "2023-06-1T10:18:03.000Z"
    //"colorID" : "3"   1985-04-12T23:20:50.52Z
}

###

PATCH http://localhost:3000/api/admins/eventManager/updateevent/6469ea568dd80c2a205a7f66
Content-Type: application/json

{
    "description": "Acini d'Uva per tutti"
}

###

DELETE http://localhost:3000/api/admins/eventManager/deleteevent/6469f58e1952e90a232336a2

### CLASSROOMS

POST http://localhost:3000/api/admins/classroomManager/createClassroom
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY3NDNiZDViNjE3MWQyZTFhZDU3NGMiLCJuYW1lIjoiQ2FwbyIsInN1cm5hbWUiOiJTdXByZW1vIiwiZW1haWwiOiJjYXBvQHN1cC5pdCIsInBhc3N3b3JkIjoiJDJiJDEwJHhPcWs1UGhJeHdoNjAzb3FzNG9VTGUyV05iRlBUWjVFNlFKNXhiM2kwSWFDd3ZEU1VtUFVLIiwiX192IjowLCJpYXQiOjE2ODU2OTc2ODl9.tPTUsOamGKc4b-0IV1Hw3hQHpvzAyMbGmAAI3jj3aqM
Content-Type: application/json

{
    "code": "B316",
    "seats": "50",
    "available": ""
}