GET http://localhost:3000/api/admins/getall

###

GET http://localhost:3000/api/admins/getadmin/645a6a34fc4bbc2a137ab299

###

POST http://localhost:3000/api/admins/signup
Content-Type: application/json

{
    "name": "Mario",
    "surname": "Rossi",
    "email": "m.rossi@gmail.it",
    "password": "pass123"
}

###

POST http://localhost:3000/api/admins/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY3NDNiZDViNjE3MWQyZTFhZDU3NGMiLCJuYW1lIjoiQ2FwbyIsInN1cm5hbWUiOiJTdXByZW1vIiwiZW1haWwiOiJjYXBvQHN1cC5pdCIsInBhc3N3b3JkIjoiJDJiJDEwJHhPcWs1UGhJeHdoNjAzb3FzNG9VTGUyV05iRlBUWjVFNlFKNXhiM2kwSWFDd3ZEU1VtUFVLIiwiX192IjowLCJpYXQiOjE2ODYzMjQ4NTN9.cmrCGEww4AP6zLUT44RC39ZXsOkYz7m58lggtKkt1ks"
}

###

DELETE http://localhost:3000/api/admins/deleteadmin/6469db0d9acd0a9eed299d56

###

PATCH http://localhost:3000/api/admins/updateAdmin/6469db0d9acd0a9eed299d56
Content-Type: application/json

{
    "email": "nanni@nonno.it",
    "password": "kikkko"
}

###

POST http://localhost:3000/api/admins/login
Content-Type: application/json

{
    "email": "capo@sup.it",
    "password": "pass123"
}

###

POST http://localhost:3000/api/admins/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY3NDNiZDViNjE3MWQyZTFhZDU3NGMiLCJuYW1lIjoiQ2FwbyIsInN1cm5hbWUiOiJTdXByZW1vIiwiZW1haWwiOiJjYXBvQHN1cC5pdCIsInBhc3N3b3JkIjoiJDJiJDEwJHhPcWs1UGhJeHdoNjAzb3FzNG9VTGUyV05iRlBUWjVFNlFKNXhiM2kwSWFDd3ZEU1VtUFVLIiwiX192IjowLCJpYXQiOjE2ODYzMjQ4NzAsImV4cCI6MTY4NjMyODQ3MH0.ixmgFRJU9bfdfU_MEhc5NnxcB6USdeqfDgVTuXIYJgo

###

DELETE http://localhost:3000/api/admins/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY3NDNiZDViNjE3MWQyZTFhZDU3NGMiLCJuYW1lIjoiQ2FwbyIsInN1cm5hbWUiOiJTdXByZW1vIiwiZW1haWwiOiJjYXBvQHN1cC5pdCIsInBhc3N3b3JkIjoiJDJiJDEwJHhPcWs1UGhJeHdoNjAzb3FzNG9VTGUyV05iRlBUWjVFNlFKNXhiM2kwSWFDd3ZEU1VtUFVLIiwiX192IjowLCJpYXQiOjE2ODYzMjQ4NTN9.cmrCGEww4AP6zLUT44RC39ZXsOkYz7m58lggtKkt1ks"
}

### STUDENTS

DELETE http://localhost:3000/api/admins/studentManager/deletestudent/6469dbe59acd0a9eed299d68

###

PATCH http://localhost:3000/api/admins/studentManager/updatestudent/6469dbe59acd0a9eed299d68
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY3NDNiZDViNjE3MWQyZTFhZDU3NGMiLCJuYW1lIjoiQ2FwbyIsInN1cm5hbWUiOiJTdXByZW1vIiwiZW1haWwiOiJjYXBvQHN1cC5pdCIsInBhc3N3b3JkIjoiJDJiJDEwJHhPcWs1UGhJeHdoNjAzb3FzNG9VTGUyV05iRlBUWjVFNlFKNXhiM2kwSWFDd3ZEU1VtUFVLIiwiX192IjowLCJpYXQiOjE2ODUwMDYwNDd9.XOFDTjNnWvQl3TA2UY8RuGZXfp7eGvaemcDQ1U_5gEg
Content-Type: application/json

{
    "email": "ninella@ehehihi",
    "student_id": "202020",
    "study_course": "veterinaria",
    "study_year": "2023"
}

###

GET http://localhost:3000/api/admins/studentManager/getstudent/6467412bd9a20eceb3b96475

###

GET http://localhost:3000/api/admins/studentManager/getstudents
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY3NDNiZDViNjE3MWQyZTFhZDU3NGMiLCJuYW1lIjoiQ2FwbyIsInN1cm5hbWUiOiJTdXByZW1vIiwiZW1haWwiOiJjYXBvQHN1cC5pdCIsInBhc3N3b3JkIjoiJDJiJDEwJHhPcWs1UGhJeHdoNjAzb3FzNG9VTGUyV05iRlBUWjVFNlFKNXhiM2kwSWFDd3ZEU1VtUFVLIiwiX192IjowLCJpYXQiOjE2ODUwMDYwNDd9.XOFDTjNnWvQl3TA2UY8RuGZXfp7eGvaemcDQ1U_5gEg

### EVENTS

GET http://localhost:3000/api/admins/eventManager/createEvent
Content-Type: application/json

{
    "summary": "Aperitivo progetto iRace",
    "location": "Povo 2 - Polo Ferrari, Trento, Italia",
    "description": "Vieni a questo aperitivo organizzato dai realizzatori del progetto iRace per scoprire di cosa si tratta!",
    "start": "2023-06-22T18:30:00.020Z",
    "end": "2023-06-22T20:00:00.000Z",
    "colorID" : "4"
}

###

PATCH http://localhost:3000/api/admins/eventManager/updateevent/6469ea568dd80c2a205a7f66
Content-Type: application/json

{
    "description": "Acini d'Uva per tutti"
}

###

DELETE http://localhost:3000/api/admins/eventManager/deleteevent/6485cac2671c6e2d821201ea

### CLASSROOMS

POST http://localhost:3000/api/admins/classroomManager/createClassroom
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY3NDNiZDViNjE3MWQyZTFhZDU3NGMiLCJuYW1lIjoiQ2FwbyIsInN1cm5hbWUiOiJTdXByZW1vIiwiZW1haWwiOiJjYXBvQHN1cC5pdCIsInBhc3N3b3JkIjoiJDJiJDEwJHhPcWs1UGhJeHdoNjAzb3FzNG9VTGUyV05iRlBUWjVFNlFKNXhiM2kwSWFDd3ZEU1VtUFVLIiwiX192IjowLCJpYXQiOjE2ODU2OTc2ODl9.tPTUsOamGKc4b-0IV1Hw3hQHpvzAyMbGmAAI3jj3aqM
Content-Type: application/json

{
    "code": "B103",
    "seats": "50",
    "available": ""
}

###

PATCH http://localhost:3000/api/admins/classroomManager/resetBooking

### SURVEYS

POST http://localhost:3000/api/admins/surveyManager/createSurvey
Content-Type: application/json

{
  "title": "Spazi verdi città",
  "link": "https://docs.google.com/forms/d/e/1FAIpQLSfOVcB7ZVxxfEvnwwpXu4SvskrH6cU80Z8NC1kUrkfC-BYANQ/viewform?usp=sf_link"
}