POST http://localhost:3000/api/students/signup
Content-Type: application/json

{
    "name": "nino",
    "surname": "d'angelo",
    "gender": "M",
    "email": "emai1@xp",
    "password": "123",
    "student_id": "124456",
    "study_course": "agraria",
    "study_year": "1945"
}

###

PATCH http://localhost:3000/api/students/646756d09bdbaaa84edacc4f
Content-Type: application/json

{
    "name": "nina",
    "surname": "d'angela",
    "gender": "F",
    "password": "pass1234"
}

###

POST http://localhost:3000/api/students/login
Content-Type: application/json

{
    "email": "emai1@xp",
    "password": "pass1234"
}

###

POST http://localhost:3000/api/students/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY3NTZkMDliZGJhYWE4NGVkYWNjNGYiLCJuYW1lIjoibmluYSIsInN1cm5hbWUiOiJkJ2FuZ2VsYSIsImdlbmRlciI6IkYiLCJlbWFpbCI6ImVtYWkxQHhwIiwicGFzc3dvcmQiOiIkMmIkMTAkcTA5RnhBcy5SNnRIbDFkd3kwMk9IZTVFQ3JvNlR2R3ZqTERMVHdSYTQ1UTA0M0QvVHhJLjYiLCJzdHVkZW50X2lkIjoiMTI0NDU2Iiwic3R1ZHlfY291cnNlIjoiYWdyYXJpYSIsInN0dWR5X3llYXIiOiIxOTQ1IiwiX192IjowLCJpYXQiOjE2ODQ0OTQyODJ9.eIbtpI847Oe3z3IRTkClKqt-M8Fm89p56_GXZB_Vsjk

###

GET http://localhost:3000/api/students