GET http://localhost:3000/api/survey/getsurveys
Authorization: Bearer eyJhbGciOoJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY3NDNiZDViNjE3MWQyZTFhZDU3NGMiLCJuYW1lIjoiQ2FwbyIsInN1cm5hbWUiOiJTdXByZW1vIiwiZW1haWwiOiJjYXBvQHN1cC5pdCIsInBhc3N3b3JkIjoiJDJiJDEwJHhPcWs1UGhJeHdoNjAzb3FzNG9VTGUyV05iRlBUWjVFNlFKNXhiM2kwSWFDd3ZEU1VtUFVLIiwiX192IjowLCJpYXQiOjE2ODY0ODA4OTksImV4cCI6MTY4NjQ4NDQ5OX0._par6m6PJsBy1OfrEGlzOowP2G4ZfppMWwhMZj9UB9A